quarkus:
  banner:
    enabled: false
  log:
    category:
      "io.quarkus":
        level: warn
      "com.norcane.zen":
        level: ${ZEN_LOG_LEVEL:off}
  native:
    resources:
      includes:
        - config/**

"%test":
  quarkus:
    jacoco:
      title: zen test coverage report
  zen:
    console:
      enabled: false