quarkus:
  banner:
    enabled: false
  jacoco:
    title: zen test coverage report
  log:
    category:
      "io.quarkus":
        level: warn
      "com.norcane.zen":
        level: ${ZEN_LOG_LEVEL:off}
  native:
    resources:
      includes:
        - config/**